<?php require 'partials.php';page_top('Om Jolt');?>
<header class="about-hero">
 <div><span class="eyebrow">JOLT BY &copy;J4RL</span><h1>Kunskap med lite mer ⚡</h1><p>Jolt är ett verktyg för att skapa lekfulla frågesporter som kan köras tillsammans i realtid eller som en aktivitet där deltagarna rör sig mellan olika stationer.</p></div>
 <div class="about-bolt" aria-hidden="true">⚡</div>
</header>
<section class="about-shell">
 <article class="about-card about-intro"><h2>Så fungerar Jolt</h2><p>Du börjar med att skapa en Jolt och fyller den med frågor, svarsalternativ, tid, poäng och – om du vill – bilder eller video. När frågorna är klara väljer du hur deltagarna ska spela.</p><div class="about-steps"><div><b>1</b><span><strong>Skapa</strong> en Jolt</span></div><div><b>2</b><span><strong>Lägg till</strong> frågor</span></div><div><b>3</b><span><strong>Välj</strong> Live eller Walking</span></div><div><b>4</b><span><strong>Spela</strong> och följ resultatet</span></div></div></article>
 <div class="about-modes">
  <article class="about-card mode-live"><span class="about-icon">⚡</span><h2>Vad är Live?</h2><p><strong>Live Jolt</strong> är ett gemensamt spel i realtid. Spelledaren visar frågorna på en större skärm och deltagarna ansluter med en sexsiffrig kod eller QR-kod och svarar på sina egna enheter.</p><p>Frågorna styrs av spelledaren, poängen påverkas av rätt svar och snabbhet, och ställningen kan visas mellan frågorna. Efteråt sparas sessionens alias, poäng per fråga och totalpoäng i resultatarkivet.</p></article>
  <article class="about-card mode-walking"><span class="about-icon">🚶</span><h2>Vad är Walking?</h2><p><strong>Walking Jolt</strong> gör varje fråga till en fysisk station. Systemet skapar utskriftsklara QR-skyltar som placeras ut, och deltagarna går runt i valfri ordning och skannar dem med mobilen.</p><p>Här används fasta poäng utan tidsbonus. Deltagarna kan ändra sina svar innan de lämnar in, och facit visas när arrangören stänger promenaden.</p></article>
 </div>
 <article class="about-card about-terms"><h2>Bra att veta</h2><dl><div><dt>Jolt</dt><dd>En samling frågor som kan återanvändas i flera spel.</dd></div><div><dt>Spelsession</dt><dd>Ett enskilt tillfälle då en Live Jolt körs. Sessionen kan namnges, skrivas ut och tas bort.</dd></div><div><dt>Alias</dt><dd>Namnet en deltagare väljer när hen ansluter till spelet.</dd></div><div><dt>Maxpoäng</dt><dd>Frågans högsta möjliga poäng. I Live påverkas utfallet även av hur snabbt svaret lämnas.</dd></div><div><dt>Resultatblad</dt><dd>En utskriftsvänlig sammanställning med deltagare, frågepoäng och totalpoäng.</dd></div><div><dt>Station</dt><dd>En fråga i Walking Jolt som låses upp genom att deltagaren skannar stationens unika QR-kod.</dd></div></dl></article>
 <article class="about-card about-donate"><div><span class="eyebrow">OM MIG</span><h2>Byggt på fritiden</h2><p>Denna app är byggd av Charlie Jarl, på fritiden.<br>Tycker du den är bra? Säg det högt. Dela den. Använd den.<br>Den är gratis av en anledning: bra saker ska inte gömmas bakom betalväggar.</p><p>Men, vill du visa uppskattning på riktigt, så uppskattas en donation enormt.<br>Helt frivilligt. Helt upp till dig.<br>Skanna PayPal-koden, om du vill, och betala det du tycker det är värt.</p></div><figure class="paypal-card"><img src="assets/paypal_qr.png" alt="PayPal QR-kod för donationer" width="180" height="180"><figcaption>PayPal</figcaption></figure></article>
</section>
<?php page_bottom();?>
