<?php require 'partials.php';$uid=require_login();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$title=trim($_POST['title']??'Ny Jolt');$s=db()->prepare('INSERT INTO jolt_quizzes(user_id,title) VALUES(?,?)');$s->bind_param('is',$uid,$title);$s->execute();redirect('editor.php?id='.$s->insert_id);}
$s=db()->prepare('SELECT COUNT(*) total FROM jolt_quizzes WHERE user_id=?');$s->bind_param('i',$uid);$s->execute();$totalQuizzes=(int)$s->get_result()->fetch_assoc()['total'];$perPage=9;$totalPages=max(1,(int)ceil($totalQuizzes/$perPage));$page=max(1,min($totalPages,(int)($_GET['page']??1)));$offset=($page-1)*$perPage;
$s=db()->prepare('SELECT q.*,COUNT(qu.id) questions FROM jolt_quizzes q LEFT JOIN jolt_questions qu ON qu.quiz_id=q.id WHERE q.user_id=? GROUP BY q.id ORDER BY q.updated_at DESC LIMIT ?,?');$s->bind_param('iii',$uid,$offset,$perPage);$s->execute();$quizzes=$s->get_result();$hasQuizzes=$totalQuizzes>0;page_top('Mina Jolt');?>
<header class="page-head"><div><span class="eyebrow">JOLTSTUDIO</span><h1>Mina Jolt</h1></div><button onclick="document.querySelector('#newQuiz').showModal()">+ Gör en ny Jolt</button></header>
<section class="quiz-grid"><?php while($q=$quizzes->fetch_assoc()):?><article class="quiz-card"><div class="quiz-cover">⚡</div><div><small><?=$q['questions']?> frågor</small><h2><?=e($q['title'])?></h2><p><?=e($q['description'])?></p><div class="actions"><a class="button secondary" href="editor.php?id=<?=$q['id']?>">Ändra</a><a class="button secondary" href="results.php?quiz=<?=$q['id']?>">Resultat</a><span class="actions-break" aria-hidden="true"></span><a class="button" href="host.php?quiz=<?=$q['id']?>">Live</a><a class="button walking-button" href="walking-setup.php?quiz=<?=$q['id']?>">Walking</a></div></div></article><?php endwhile?><article class="quiz-card empty" onclick="newQuiz.showModal()"><b>+</b><span><?=$hasQuizzes?'Gör en ny Jolt':'Gör din första Jolt'?></span></article></section>
<?php if($totalPages>1):$visible=array_values(array_unique(array_filter([1,$page-2,$page-1,$page,$page+1,$page+2,$totalPages],fn($p)=>$p>=1&&$p<=$totalPages)));sort($visible);?><nav class="pagination" aria-label="Sidnavigering"><a class="pagination-arrow <?=$page===1?'disabled':''?>" href="?page=<?=max(1,$page-1)?>" aria-label="Föregående sida">←</a><?php $last=0;foreach($visible as $p):if($last&&$p>$last+1):?><span class="pagination-gap">…</span><?php endif?><a class="<?=$p===$page?'active':''?>" href="?page=<?=$p?>" <?=$p===$page?'aria-current="page"':''?>><?=$p?></a><?php $last=$p;endforeach?><a class="pagination-arrow <?=$page===$totalPages?'disabled':''?>" href="?page=<?=min($totalPages,$page+1)?>" aria-label="Nästa sida">→</a></nav><?php endif?>
<dialog id="newQuiz"><form method="post"><button type="button" class="close" onclick="newQuiz.close()">×</button><h2>Gör en ny Jolt</h2><input type="hidden" name="csrf" value="<?=csrf()?>"><label>Titel</label><input name="title" required maxlength="140" autofocus><button>Gör Jolten →</button></form></dialog>
<?php page_bottom();?>
