<?php
require 'partials.php'; $uid=require_login(); $id=(int)($_GET['id']??0);
$s=db()->prepare('SELECT * FROM quizzes WHERE id=? AND user_id=?');$s->bind_param('ii',$id,$uid);$s->execute();$quiz=$s->get_result()->fetch_assoc();if(!$quiz){http_response_code(404);exit('Quizet hittades inte.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $action=$_POST['action']??'';
 if($action==='details'){$title=trim($_POST['title']);$desc=trim($_POST['description']);$pub=isset($_POST['is_public'])?1:0;$s=db()->prepare('UPDATE quizzes SET title=?,description=?,is_public=? WHERE id=? AND user_id=?');$s->bind_param('ssiii',$title,$desc,$pub,$id,$uid);$s->execute();}
 if($action==='question'){
  $qid=(int)($_POST['question_id']??0);$text=trim($_POST['text']);$type=in_array($_POST['type']??'', ['single','multiple','truefalse'],true)?$_POST['type']:'single';$time=max(5,min(120,(int)$_POST['time_limit']));$points=max(100,min(5000,(int)$_POST['points']));$mediaPath=null;$mediaType=null;
  if(isset($_FILES['media'])&&$_FILES['media']['error']===UPLOAD_ERR_OK){if($_FILES['media']['size']>MAX_UPLOAD_BYTES)exit('Filen är för stor.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['media']['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','video/mp4'=>'mp4','video/webm'=>'webm'];if(!isset($allowed[$mime]))exit('Filtypen stöds inte.');if(!is_dir('uploads'))mkdir('uploads',0775,true);$mediaPath='uploads/'.bin2hex(random_bytes(12)).'.'.$allowed[$mime];move_uploaded_file($_FILES['media']['tmp_name'],$mediaPath);$mediaType=str_starts_with($mime,'image/')?'image':'video';}
  if($qid){$s=db()->prepare('UPDATE questions q JOIN quizzes z ON z.id=q.quiz_id SET q.text=?,q.type=?,q.time_limit=?,q.points=?,q.media_path=COALESCE(?,q.media_path),q.media_type=COALESCE(?,q.media_type) WHERE q.id=? AND z.user_id=?');$s->bind_param('ssiissii',$text,$type,$time,$points,$mediaPath,$mediaType,$qid,$uid);$s->execute();db()->query('DELETE FROM answers WHERE question_id='.$qid);}
  else{$pos=(int)db()->query('SELECT COALESCE(MAX(position),0)+1 p FROM questions WHERE quiz_id='.$id)->fetch_assoc()['p'];$s=db()->prepare('INSERT INTO questions(quiz_id,position,text,type,time_limit,points,media_path,media_type) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('iissiiss',$id,$pos,$text,$type,$time,$points,$mediaPath,$mediaType);$s->execute();$qid=$s->insert_id;}
  $answers=$_POST['answers']??[];$correct=array_map('intval',$_POST['correct']??[]);foreach($answers as $i=>$answer){$answer=trim($answer);if($answer==='')continue;$ok=in_array((int)$i,$correct,true)?1:0;$p=$i+1;$s=db()->prepare('INSERT INTO answers(question_id,text,is_correct,position) VALUES(?,?,?,?)');$s->bind_param('isii',$qid,$answer,$ok,$p);$s->execute();}
 }
 if($action==='delete_question'){$qid=(int)$_POST['question_id'];$s=db()->prepare('DELETE q FROM questions q JOIN quizzes z ON z.id=q.quiz_id WHERE q.id=? AND z.user_id=?');$s->bind_param('ii',$qid,$uid);$s->execute();}
 redirect('editor.php?id='.$id);
}
$s=db()->prepare('SELECT * FROM questions WHERE quiz_id=? ORDER BY position');$s->bind_param('i',$id);$s->execute();$questions=$s->get_result();page_top('Redigera quiz');?>
<header class="page-head"><div><a href="dashboard.php">← Mina quiz</a><h1><?=e($quiz['title'])?></h1></div><a class="button" href="host.php?quiz=<?=$id?>">Starta Jolt ⚡</a></header>
<section class="editor-layout"><aside><form method="post" class="panel"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="details"><label>Titel</label><input name="title" value="<?=e($quiz['title'])?>" required><label>Beskrivning</label><textarea name="description"><?=e($quiz['description'])?></textarea><label class="check"><input type="checkbox" name="is_public" <?=$quiz['is_public']?'checked':''?>> Publikt quiz</label><button>Spara detaljer</button></form></aside><div><div class="section-title"><h2>Frågor</h2><button onclick="openQuestion()">+ Lägg till</button></div>
<?php $n=0;while($q=$questions->fetch_assoc()):$n++;$a=db()->query('SELECT * FROM answers WHERE question_id='.(int)$q['id'].' ORDER BY position')->fetch_all(MYSQLI_ASSOC);?><article class="question-row"><b><?=$n?></b><div><small><?=e($q['type'])?> · <?=$q['time_limit']?> sek · <?=$q['points']?> p</small><h3><?=e($q['text'])?></h3><p><?=implode(' · ',array_map(fn($x)=>($x['is_correct']?'✓ ':'').e($x['text']),$a))?></p></div><button class="secondary" data-question='<?=e(json_encode(array_merge($q,['answers'=>$a]),JSON_UNESCAPED_UNICODE))?>' onclick="editQuestion(this)">Redigera</button><form method="post" onsubmit="return confirm('Ta bort frågan?')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_question"><input type="hidden" name="question_id" value="<?=$q['id']?>"><button class="danger">×</button></form></article><?php endwhile?></div></section>
<dialog id="questionDialog"><form method="post" enctype="multipart/form-data"><button type="button" class="close" onclick="questionDialog.close()">×</button><h2 id="dialogTitle">Ny fråga</h2><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="question"><input type="hidden" name="question_id" id="questionId"><label>Fråga</label><textarea name="text" id="questionText" required></textarea><div class="form-grid"><div><label>Typ</label><select name="type" id="questionType"><option value="single">Ett rätt svar</option><option value="multiple">Flera rätta svar</option><option value="truefalse">Sant / falskt</option></select></div><div><label>Tid (sek)</label><input type="number" name="time_limit" id="questionTime" value="20" min="5" max="120"></div><div><label>Maxpoäng</label><input type="number" name="points" id="questionPoints" value="1000" min="100" max="5000"></div></div><label>Bild eller video (max 25 MB)</label><input type="file" name="media" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm"><label>Svarsalternativ — markera rätt</label><div id="answers"></div><button type="button" class="secondary" onclick="addAnswer()">+ Svar</button><button>Spara fråga</button></form></dialog>
<script src="assets/editor.js"></script><?php page_bottom();?>
