<?php
require 'partials.php';$uid=require_login();$id=(int)($_GET['id']??0);$s=db()->prepare('SELECT w.*,q.title,q.description FROM jolt_walking_jolts w JOIN jolt_quizzes q ON q.id=w.quiz_id WHERE w.id=? AND w.host_user_id=?');$s->bind_param('ii',$id,$uid);$s->execute();$walk=$s->get_result()->fetch_assoc();if(!$walk)exit('Walking Jolten hittades inte.');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';if($action==='close')db()->query("UPDATE jolt_walking_jolts SET status='closed',closed_at=NOW() WHERE id=$id");if($action==='open')db()->query("UPDATE jolt_walking_jolts SET status='open',closed_at=NULL WHERE id=$id");redirect('walking-host.php?id='.$id);}
$questions=db()->query('SELECT id,position,text FROM jolt_questions WHERE quiz_id='.(int)$walk['quiz_id'].' ORDER BY position')->fetch_all(MYSQLI_ASSOC);$players=db()->query('SELECT p.*,(SELECT COUNT(*) FROM jolt_walking_responses r WHERE r.player_id=p.id) answered FROM jolt_walking_players p WHERE walking_jolt_id='.$id.' ORDER BY score DESC,submitted_at IS NULL,submitted_at,joined_at')->fetch_all(MYSQLI_ASSOC);$playRoot=PLAY_URL?:((isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'?'https':'http').'://'.$_SERVER['HTTP_HOST'].rtrim(dirname($_SERVER['SCRIPT_NAME']),'/\\'));$playBase=rtrim($playRoot,'/').'/walk.php';
page_top('Walking Jolt');?>
<header class="page-head no-print"><div><a href="dashboard.php">← Mina Jolt</a><span class="eyebrow">WALKING JOLT · <?=strtoupper($walk['status'])?></span><h1><?=e($walk['title'])?></h1></div><div class="actions"><button class="secondary" onclick="window.print()">Skriv ut stationer</button><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="<?=$walk['status']==='open'?'close':'open'?>"><button class="<?=$walk['status']==='open'?'danger':'walking-button'?>"><?=$walk['status']==='open'?'Stäng och visa resultat':'Öppna igen'?></button></form></div></header>
<section class="walking-host-summary no-print"><div class="panel"><span class="eyebrow">DELTAGARKOD</span><h2 class="walking-code"><?=$walk['code']?></h2><p><a href="<?=e($playBase.'?code='.$walk['code'])?>"><?=e($playBase.'?code='.$walk['code'])?></a></p></div><div class="panel"><span class="eyebrow">LÄGE</span><h2><?=$walk['status']==='open'?'Promenaden är öppen':'Resultatet är klart'?></h2><p><?=count($players)?> deltagare · <?=count(array_filter($players,fn($p)=>$p['submitted_at']))?> inlämnade</p></div></section>
<?php if($walk['status']==='closed'):?><section class="walking-results no-print"><h2>Resultat</h2><ol class="walk-ranking"><?php foreach($players as $i=>$p):?><li><b><?=$i+1?></b><span><?=e($p['avatar'])?> <?=e($p['name'])?></span><strong><?=$p['score']?> p</strong></li><?php endforeach?></ol></section><?php else:?><section class="walking-results no-print"><h2>Deltagare</h2><ol class="walk-ranking"><?php foreach($players as $p):?><li><span><?=e($p['avatar'])?> <?=e($p['name'])?></span><strong><?=$p['answered']?>/<?=count($questions)?> <?=$p['submitted_at']?'✓ Inlämnad':''?></strong></li><?php endforeach?></ol></section><?php endif?>
<section class="station-sheets"><article class="station-sheet start-sheet"><span class="eyebrow">WALKING JOLT</span><h1><?=e($walk['title'])?></h1><div class="qr" data-url="<?=e($playBase.'?code='.$walk['code'])?>"></div><h2>Skanna för att starta</h2><p>eller gå till <?=e($playBase)?> och ange <b><?=$walk['code']?></b></p></article><?php foreach($questions as $q):$key=hash_hmac('sha256',(string)$q['id'],$walk['scan_secret']);$url=$playBase.'?walk='.$id.'&station='.$q['position'].'&key='.$key;?><article class="station-sheet"><span class="eyebrow">WALKING JOLT</span><h1>Fråga <?=$q['position']?></h1><div class="qr" data-url="<?=e($url)?>"></div><p>Skanna QR-koden för att låsa upp frågan och svara.</p></article><?php endforeach?></section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><script>document.querySelectorAll('.qr').forEach(el=>new QRCode(el,{text:el.dataset.url,width:220,height:220,correctLevel:QRCode.CorrectLevel.H}))</script>
<?php page_bottom();?>
