<?php
require 'partials.php';
$code=preg_replace('/\D/','',$_GET['code']??'');$walkId=(int)($_GET['walk']??($_POST['walk_id']??0));$station=(int)($_GET['station']??($_POST['station']??0));$key=$_GET['key']??($_POST['key']??'');
if($code){$s=db()->prepare("SELECT w.*,q.title,q.description FROM jolt_walking_jolts w JOIN jolt_quizzes q ON q.id=w.quiz_id WHERE w.code=?");$s->bind_param('s',$code);$s->execute();$walk=$s->get_result()->fetch_assoc();$walkId=(int)($walk['id']??0);}elseif($walkId){$s=db()->prepare('SELECT w.*,q.title,q.description FROM jolt_walking_jolts w JOIN jolt_quizzes q ON q.id=w.quiz_id WHERE w.id=?');$s->bind_param('i',$walkId);$s->execute();$walk=$s->get_result()->fetch_assoc();}else{$walk=null;}
if(!$walk){page_top('Walking Jolt');?><section class="join-page"><form class="join-card" method="get"><span class="eyebrow">WALKING JOLT</span><h1>Gå en Jolt</h1><label>Promenadkod</label><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required><button>Fortsätt →</button></form></section><?php page_bottom();exit;}
$cookieName='walking_'.$walkId;$player=null;if(!empty($_COOKIE[$cookieName])){$token=preg_replace('/[^a-f0-9]/','',$_COOKIE[$cookieName]);$s=db()->prepare('SELECT * FROM jolt_walking_players WHERE token=? AND walking_jolt_id=?');$s->bind_param('si',$token,$walkId);$s->execute();$player=$s->get_result()->fetch_assoc();}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='join'){$name=trim(mb_substr($_POST['name']??'',0,40));$avatar=mb_substr($_POST['avatar']??'⚡',0,12);if(!$name)$error='Ange ett namn.';elseif($walk['status']!=='open')$error='Promenaden är stängd.';else{try{$token=bin2hex(random_bytes(24));$s=db()->prepare('INSERT INTO jolt_walking_players(walking_jolt_id,token,name,avatar) VALUES(?,?,?,?)');$s->bind_param('isss',$walkId,$token,$name,$avatar);$s->execute();setcookie($cookieName,$token,['expires'=>time()+60*60*24*30,'path'=>'/','httponly'=>true,'samesite'=>'Lax']);$target='walk.php?walk='.$walkId;if($station&&$key)$target.='&station='.$station.'&key='.rawurlencode($key);redirect($target);}catch(mysqli_sql_exception $e){$error='Namnet används redan i denna Walking Jolt.';}}}
 if(!$player&&$action!=='join')exit('Deltagaren hittades inte.');
 if($action==='answer'&&$walk['status']==='open'&&!$player['submitted_at']){$qid=(int)$_POST['question_id'];$answerId=(int)$_POST['answer_id'];$s=db()->prepare('SELECT q.points,a.is_correct FROM jolt_walking_unlocks u JOIN jolt_questions q ON q.id=u.question_id JOIN jolt_answers a ON a.question_id=q.id AND a.id=? WHERE u.player_id=? AND u.question_id=?');$s->bind_param('iii',$answerId,$player['id'],$qid);$s->execute();$answer=$s->get_result()->fetch_assoc();if($answer){$ok=(int)$answer['is_correct'];$points=$ok?(int)$answer['points']:0;$s=db()->prepare('INSERT INTO jolt_walking_responses(player_id,question_id,answer_id,is_correct,points_awarded) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE answer_id=VALUES(answer_id),is_correct=VALUES(is_correct),points_awarded=VALUES(points_awarded)');$s->bind_param('iiiii',$player['id'],$qid,$answerId,$ok,$points);$s->execute();db()->query('UPDATE jolt_walking_players SET score=(SELECT COALESCE(SUM(points_awarded),0) FROM jolt_walking_responses WHERE player_id='.(int)$player['id'].') WHERE id='.(int)$player['id']);}redirect('walk.php?walk='.$walkId.'&station='.$station);}
 if($action==='submit'&&$walk['status']==='open'&&!$player['submitted_at']){db()->query('UPDATE jolt_walking_players SET submitted_at=NOW() WHERE id='.(int)$player['id']);redirect('walk.php?walk='.$walkId);}
}
if(!$player){page_top('Gå med i Walking Jolt');?><section class="join-page"><form class="join-card" method="post"><span class="eyebrow">DU GÅR MED I</span><h1><?=e($walk['title'])?></h1><?php if(isset($error)):?><p class="error"><?=e($error)?></p><?php endif?><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="join"><input type="hidden" name="walk_id" value="<?=$walkId?>"><input type="hidden" name="station" value="<?=$station?>"><input type="hidden" name="key" value="<?=e($key)?>"><label>Välj avatar</label><div class="avatars"><?php foreach(['⚡','🦊','🐼','🐸','🦄','🚀'] as $i=>$a):?><label><input type="radio" name="avatar" value="<?=$a?>" <?=$i?'':'checked'?>><?=$a?></label><?php endforeach?></div><label>Ditt namn</label><input name="name" maxlength="40" required><button>Starta promenaden 🚶</button></form></section><?php page_bottom();exit;}
if($station&&$key&&$walk['status']==='open'){$s=db()->prepare('SELECT id FROM jolt_questions WHERE quiz_id=? AND position=?');$s->bind_param('ii',$walk['quiz_id'],$station);$s->execute();$q=$s->get_result()->fetch_assoc();if($q&&hash_equals(hash_hmac('sha256',(string)$q['id'],$walk['scan_secret']),$key)){$s=db()->prepare('INSERT IGNORE INTO jolt_walking_unlocks(player_id,question_id) VALUES(?,?)');$s->bind_param('ii',$player['id'],$q['id']);$s->execute();redirect('walk.php?walk='.$walkId.'&station='.$station);}else{$scanError='QR-koden är inte giltig.';}}
$total=(int)db()->query('SELECT COUNT(*) c FROM jolt_questions WHERE quiz_id='.(int)$walk['quiz_id'])->fetch_assoc()['c'];$answered=(int)db()->query('SELECT COUNT(*) c FROM jolt_walking_responses WHERE player_id='.(int)$player['id'])->fetch_assoc()['c'];
if($station){$s=db()->prepare('SELECT q.* FROM jolt_questions q JOIN jolt_walking_unlocks u ON u.question_id=q.id AND u.player_id=? WHERE q.quiz_id=? AND q.position=?');$s->bind_param('iii',$player['id'],$walk['quiz_id'],$station);$s->execute();$question=$s->get_result()->fetch_assoc();if($question){$answers=db()->query('SELECT id,text'.($walk['status']==='closed'?',is_correct':'').' FROM jolt_answers WHERE question_id='.(int)$question['id'].' ORDER BY position')->fetch_all(MYSQLI_ASSOC);$response=db()->query('SELECT * FROM jolt_walking_responses WHERE player_id='.(int)$player['id'].' AND question_id='.(int)$question['id'])->fetch_assoc();}}
page_top('Walking Jolt');?>
<section class="walk-app"><header class="walk-top"><a href="walk.php?walk=<?=$walkId?>" class="logo">JOLT<span>⚡</span></a><span><?=e($player['avatar'])?> <?=e($player['name'])?></span><strong><?=$answered?>/<?=$total?></strong></header>
<?php if(isset($scanError)):?><p class="error"><?=e($scanError)?></p><?php endif?>
<?php if(isset($question)):?><article class="walk-question"><span class="eyebrow">STATION <?=$question['position']?></span><h1><?=e($question['text'])?></h1><?php if($question['media_path']):?><?=$question['media_type']==='video'?'<video class="question-media" src="'.e($question['media_path']).'" autoplay loop muted playsinline></video>':'<img class="question-media" src="'.e($question['media_path']).'" alt="">'?><?php endif?><form method="post" class="walk-answers"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="answer"><input type="hidden" name="walk_id" value="<?=$walkId?>"><input type="hidden" name="station" value="<?=$station?>"><input type="hidden" name="question_id" value="<?=$question['id']?>"><?php foreach($answers as $i=>$a):?><label class="walk-answer <?=$walk['status']==='closed'&&$a['is_correct']?'correct':''?>"><input type="radio" name="answer_id" value="<?=$a['id']?>" <?=($response['answer_id']??0)==$a['id']?'checked':''?> <?=$walk['status']==='open'&&!$player['submitted_at']?'':'disabled'?>><b><?=['◆','●','▲','■'][$i%4]?></b><span><?=e($a['text'])?></span></label><?php endforeach?><?php if($walk['status']==='open'&&!$player['submitted_at']):?><button>Spara svar</button><?php endif?></form><?php if($walk['status']==='closed'):?><p class="walk-feedback <?=($response['is_correct']??0)?'correct':''?>"><?=($response['is_correct']??0)?'Rätt! +'.$response['points_awarded'].' poäng':'Inte rätt denna gång.'?></p><?php endif?><a class="button secondary" href="walk.php?walk=<?=$walkId?>">← Mina stationer</a></article>
<?php else:?><div class="walk-home"><span class="eyebrow">WALKING JOLT</span><h1><?=e($walk['title'])?></h1><?php if($walk['status']==='closed'):$ranking=db()->query('SELECT name,avatar,score FROM jolt_walking_players WHERE walking_jolt_id='.$walkId.' ORDER BY score DESC,submitted_at,joined_at')->fetch_all(MYSQLI_ASSOC);?><h2>Resultat</h2><ol class="walk-ranking"><?php foreach($ranking as $i=>$p):?><li><b><?=$i+1?></b><span><?=e($p['avatar'])?> <?=e($p['name'])?></span><strong><?=$p['score']?> p</strong></li><?php endforeach?></ol><?php elseif($player['submitted_at']):?><div class="waiting"><b>✓</b><h2>Promenaden är inlämnad</h2><p>Facit och resultat visas när arrangören stänger.</p></div><?php else:$unlocked=db()->query('SELECT q.position,q.text,r.answer_id FROM jolt_walking_unlocks u JOIN jolt_questions q ON q.id=u.question_id LEFT JOIN jolt_walking_responses r ON r.player_id=u.player_id AND r.question_id=q.id WHERE u.player_id='.(int)$player['id'].' ORDER BY q.position')->fetch_all(MYSQLI_ASSOC);?><div class="walk-progress"><div style="width:<?=round($answered/max(1,$total)*100)?>%"></div></div><p><?=$answered?> av <?=$total?> frågor besvarade. Skanna QR-koden vid nästa station.</p><div class="unlocked-stations"><?php foreach($unlocked as $q):?><a href="walk.php?walk=<?=$walkId?>&station=<?=$q['position']?>"><b><?=$q['position']?></b><span><?=e($q['text'])?></span><strong><?=$q['answer_id']?'✓':'→'?></strong></a><?php endforeach?></div><form method="post" onsubmit="return confirm('Lämna in promenaden? Därefter kan svaren inte ändras.')"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="submit"><input type="hidden" name="walk_id" value="<?=$walkId?>"><button <?=$answered?'':'disabled'?>>Lämna in Walking Jolt</button></form><?php endif?></div><?php endif?></section>
<?php page_bottom();?>
